account/urls.py
#==>Library Import
from django.urls import path
#==>Local Import
from . import views


app_name='account'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('verify-phone/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('profile/', views.EditProfileView.as_view(), name='edit_profile'),
    path('address/', views.AddressView.as_view(), name='profile_address'),
    path('update-phone/', views.UpdatePhoneNumberView.as_view(), name='update_phone'),
    path('change-username/', views.ChangeUsernameView.as_view(), name='change_username'),
    path('activate-email/', views.SendActivateEmailView.as_view(), name='email-activate'),
    path('activate/<uidb64>/<token>/<email>/', views.ActivateEmailView.as_view(), name='activate'),
    path('reset-password/', views.UserPasswordResetView.as_view(), name='reset_password'),
	path('reset-password/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
	path('confirm-password/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('confirm-password/complete', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

order/urls.py
#==>Library Import
from django.urls import path
#==>Local Import
from . import views


app_name = 'orders'
urlpatterns = [
	path('create/', views.OrderCreateView.as_view(), name='order_create'),
	path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
	path('cart/', views.CartView.as_view(), name='cart'),
	path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
	path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
	path('create/', views.OrderCreateView.as_view(), name='order_create'),
	path('<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
	path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
	path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
	path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon'),

]

shop/urls.py
#==>Library Import
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
#==>Library Import
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth import get_user_model
from django.db import models
#==>Local Import
from product.models import Variant
from account.models import ProfileAddress
from product.models import TimeStamp


class Order(TimeStamp):
	user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='orders', verbose_name='کاربر')
	paid = models.BooleanField(default=False, verbose_name='پرداخت شده؟')
	discount = models.IntegerField(blank=True, null=True, default=None, verbose_name='تخفیف')
	address = models.ForeignKey(ProfileAddress, on_delete=models.CASCADE, null=True, blank=True, verbose_name='آدرس')

	class Meta:
		ordering = ('paid', '-updated')
		verbose_name = 'سفارش'
		verbose_name_plural = 'سفارشات'

	def __str__(self):
		return f'{self.user} - {str(self.id)}'

	
	def get_total_price(self):
		total = sum(item.get_cost() for item in self.orderitem_order.all())
		if self.discount:
			discount_price = (self.discount / 100) * total
			return int(total - discount_price)
		return total
	get_total_price.short_description = 'قیمت تمام شده (تخفیف محصول/کدتخفیف)'


class OrderItem(TimeStamp):
	order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderitem_order', verbose_name='سفارش')
	variant = models.ForeignKey(Variant, on_delete=models.CASCADE, verbose_name='محصول')
	price = models.IntegerField(verbose_name='قیمت')
	quantity = models.IntegerField(default=1, verbose_name='تعداد')

	class Meta:
		verbose_name = 'محصول ثبت شده'
		verbose_name_plural = 'محصولات ثبت شده'

	def __str__(self):
		return str(self.id)

	def get_cost(self):
		return self.price * self.quantity


class Coupon(models.Model):
	code = models.CharField(max_length=30, unique=True)
	valid_from = models.DateTimeField()
	valid_to = models.DateTimeField()
	discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(90)])
	active = models.BooleanField(default=False)

	class Meta:
		verbose_name = 'کد تخفیف'
		verbose_name_plural = 'کد های تخفیف'

	def __str__(self):
		return self.code

order/forms.py
#==>Library Import
from django import forms
#==>Local Import
from account.models import Profile


class CartAddForm(forms.Form):
	quantity = forms.IntegerField(min_value=1, max_value=9, widget=forms.NumberInput(attrs={'value':'1', 'class':'form-control-sm'}))


class CouponApplyForm(forms.Form):
	code = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'کوپن'}))


class OrderForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'national_code', 'address']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'نام'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'نام خانوادگی'})
        self.fields['national_code'].widget.attrs.update({'class': 'form-control', 'placeholder': 'کد ملی'})
        self.fields['address'].widget.attrs.update({'class': 'form-control', 'placeholder': 'آدرس'})

order/views.py
#==>Library Import
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.conf import settings
from django.views import View
import requests
import datetime
import json
#==>Local Import
from .forms import CartAddForm, CouponApplyForm, OrderForm
from .models import Order, OrderItem, Coupon
from account.models import ProfileAddress
from product.models import Variant
from .cart import Cart


class CartView(View):
	def get(self, request):
		cart = Cart(request)
		return render(request, 'orders/cart.html', {'cart':cart})


class CartAddView(View):
	def post(self, request, product_id):
		cart = Cart(request)
		product = Variant.objects.get(id=product_id)
		form = CartAddForm(request.POST)
		if form.is_valid():
			cart.add(product, form.cleaned_data['quantity'])
		messages.success(request, 'محصول مورد نظر به سبد خرید اضافه شد', 'success')
		return redirect('product:detail', product.slug)


class CartRemoveView(View):
	def get(self, request, product_id):
		cart = Cart(request)
		product = get_object_or_404(Variant, id=product_id)
		cart.remove(product)
		messages.success(request, 'محصول مورد نظر از سبد خرید حذف شد', 'warning')
		return redirect('orders:cart')


class OrderDetailView(LoginRequiredMixin, View):
	form_class = CouponApplyForm

	def get(self, request, order_id):
		order_form = OrderForm(instance=request.user.profile)
		order = get_object_or_404(Order, id=order_id)
		user_address = ProfileAddress.objects.filter(user_id=request.user.id)
		return render(request, 'orders/order.html', {'order':order, 'form':self.form_class, 'order_form':order_form, 'user_address':user_address})

	def post(self, request, order_id):
		order_form = OrderForm(request.POST, instance=request.user.profile)
		if order_form.is_valid():
			new_order = order_form.save(commit=False)
			new_order.user = request.user
			new_order.save()
			order_address = get_object_or_404(Order, id=order_id)
			order_address.address = order_form.cleaned_data['address']
			order_address.save()
			return redirect('orders:order_detail', order_id)


class OrderCreateView(LoginRequiredMixin, View):
	def get(self, request):
		cart = Cart(request)
		order = Order.objects.create(user=request.user)
		for item in cart:
			OrderItem.objects.create(order=order, variant=item['product'], price=item['total_price'], quantity=item['quantity'])
		cart.clear()
		return redirect('orders:order_detail', order.id)


MERCHANT = settings.MERCHANT
ZP_API_REQUEST = "https://api.zarinpal.com/pg/v4/payment/request.json"
ZP_API_VERIFY = "https://api.zarinpal.com/pg/v4/payment/verify.json"
ZP_API_STARTPAY = "https://www.zarinpal.com/pg/StartPay/{authority}"
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"
CallbackURL = 'http://127.0.0.1:8000/order/verify/'

class OrderPayView(LoginRequiredMixin, View):
	def get(self, request, order_id):
		order = Order.objects.get(id=order_id)
		request.session['order_pay'] = {
			'order_id': order.id,
		}
		req_data = {
			"merchant_id": MERCHANT,
			"amount": order.get_total_price(),
			"callback_url": CallbackURL,
			"description": description,
			"metadata": {"mobile": request.user.phone, "email": request.user.email}
		}
		req_header = {"accept": "application/json",
					  "content-type": "application/json'"}
		req = requests.post(url=ZP_API_REQUEST, data=json.dumps(
			req_data), headers=req_header)
		authority = req.json()['data']['authority']
		if len(req.json()['errors']) == 0:
			return redirect(ZP_API_STARTPAY.format(authority=authority))
		else:
			e_code = req.json()['errors']['code']
			e_message = req.json()['errors']['message']
			return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")


class OrderVerifyView(LoginRequiredMixin, View):
	def get(self, request):
		order_id = request.session['order_pay']['order_id']
		order = Order.objects.get(id=int(order_id))
		t_status = request.GET.get('Status')
		t_authority = request.GET['Authority']
		if request.GET.get('Status') == 'OK':
			req_header = {"accept": "application/json",
						  "content-type": "application/json'"}
			req_data = {
				"merchant_id": MERCHANT,
				"amount": order.get_total_price(),
				"authority": t_authority
			}
			req = requests.post(url=ZP_API_VERIFY, data=json.dumps(req_data), headers=req_header)
			if len(req.json()['errors']) == 0:
				t_status = req.json()['data']['code']
				if t_status == 100:
					order.paid = True
					order.orderitem_order.sell += 1
					order.save()
					return HttpResponse('Transaction success.\nRefID: ' + str(
						req.json()['data']['ref_id']
					))
				elif t_status == 101:
					return HttpResponse('Transaction submitted : ' + str(
						req.json()['data']['message']
					))
				else:
					return HttpResponse('Transaction failed.\nStatus: ' + str(
						req.json()['data']['message']
					))
			else:
				e_code = req.json()['errors']['code']
				e_message = req.json()['errors']['message']
				return HttpResponse(f"Error code: {e_code}, Error Message: {e_message}")
		else:
			return HttpResponse('Transaction failed or canceled by user')


class CouponApplyView(LoginRequiredMixin, View):
	form_class = CouponApplyForm

	def post(self, request, order_id):
		now = datetime.datetime.now()
		form = self.form_class(request.POST)
		if form.is_valid():
			code = form.cleaned_data['code']
			try:
				coupon = Coupon.objects.get(code__exact=code, valid_from__lte=now, valid_to__gte=now, active=True)
			except Coupon.DoesNotExist:
				messages.error(request, 'this coupon does not exists', 'danger')
				return redirect('orders:order_detail', order_id)
			order = Order.objects.get(id=order_id)
			order.discount = coupon.discount
			order.save()
			messages.success(request, "کوپن اعمال شد", 'success')
		return redirect('orders:order_detail', order_id)

order/templates/orders/cart.html
{% extends 'base.html' %}
{% block title %}محصول {{product.title}}{% endblock title %}

{% block content %}

<!-- START MAIN CONTENT -->
<div class="main_content">

    <!-- START SECTION SHOP -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive shop_cart_table">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th class="product-thumbnail">&nbsp;</th>
                                    <th class="product-name">محصول</th>
                                    <th class="product-price">قیمت</th>
                                    <th class="product-quantity">تعداد</th>
                                    <th class="product-subtotal">جمع</th>
                                    <th class="product-remove">حذف</th>
                                </tr>
                            </thead>
                            <tbody>

                                {% for item in cart %}
                                <tr>
                                    <td class="product-thumbnail"><a href="#"><img src="{{item.product.image.url}}" alt="product1"></a></td>
                                    <td class="product-name" data-title="محصول"><a href="#">{{item.product}}</a></td>
                                    <td class="product-price" data-title="قیمت">{{item.price}} تومان</td>
                                    <td class="product-quantity" data-title="تعداد"><div class="quantity">
                                    <input type="button" value="-" class="minus">
                                    <input type="text" name="quantity" value="{{item.quantity}}" title="Qty" class="qty" size="4">
                                    <input type="button" value="+" class="plus">
                                  </div></td>
                                      <td class="product-subtotal" data-title="جمع">{{item.total_price}} تومان</td>
                                    <td class="product-remove" data-title="حذف"><a href="{% url 'orders:cart_remove' item.product.id %}"><i class="ti-close"></i></a></td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="medium_divider"></div>
                    <div class="divider center_icon"><i class="ti-shopping-cart-full"></i></div>
                    <div class="medium_divider"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="border p-3 p-md-4">
                        <div class="heading_s1 mb-3">
                            <h6>جمع سبد خرید</h6>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td class="cart_total_label">جمع سبد خرید</td>
                                        <td class="cart_total_amount">{{cart.get_total_price}} تومان</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <a href="{% url 'orders:order_create' %}" class="btn btn-fill-out">ادامه</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END SECTION SHOP -->
    
    </div>
    <!-- END MAIN CONTENT -->
{% endblock content %}

order/templates/orders/order.html
{% extends 'base.html' %}
{% block title %}سفارش محصولات{% endblock title %}

{% block content %}

    <!-- START MAIN CONTENT -->
<div class="main_content">

    <!-- START SECTION SHOP -->
    <div class="section">
        <div class="container">
            <div class="row">
            </div>
            <div class="row">
                <div class="table-responsive shop_cart_table">
                	<table class="table">
                        <tfoot>
                        	<tr>
                            	<td colspan="6" class="px-0">
                                	<div class="row no-gutters align-items-center">

                                    	<div class="col-lg-4 col-md-6 mb-3 mb-md-0">
                                            <form action="{% url 'orders:apply_coupon' order.id %}" method="post" class="coupon field_form input-group">
                                                {% csrf_token %}
                                                {{form.code}}
                                                <div class="input-group-append">
                                                	<button class="btn btn-fill-out btn-sm" type="submit">کوپن</button>
                                                </div>
                                            </form>
                                    	</div>
                                        <div class="col-lg-8 col-md-6 text-left text-md-right">
                                            <button class="btn btn-line-fill btn-sm" type="submit">به روز رسانی سبد خرید</button>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <div class="col-12">
                    <div class="medium_divider"></div>
                    <div class="divider center_icon"><i class="ti-shopping-cart-full"></i></div>
                    <div class="medium_divider"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="heading_s1 mb-3">
                        <h6>محاسبه هزینه ارسال</h6>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                            <div class="form-group">
                                {{order_form.first_name.label_tag}}
                                {{order_form.first_name}}
                            </div>
                            <div class="form-group">
                                {{order_form.last_name.label_tag}}
                                {{order_form.last_name}}
                            </div>
                            <div class="form-group">
                                {{order_form.national_code.label_tag}}
                                {{order_form.national_code}}
                            </div>
                            <div class="form-group">
                                {{order_form.address.label_tag}}
                                <select name="address" class="form-control" placeholder="آدرس" id="id_address">
                                    <option value selected>---------</option>
                                    {% for item in user_address %}
                                        <option value="{{item.id}}">{{item.address}}</option>
                                    {% endfor %}
                                </select>
                                <label>در صورت موجود نبودن آدرس از این <a href="{% url 'account:edit_profile' %}">لینک</a> اضافه کنید</label>
                            </div>
                            <button type="submit" class="btn btn-fill-out btn-block">ترتیب سفارش</button>
                    </form>
                </div>
                <div class="col-md-6">
                    <div class="border p-3 p-md-4">
                        <div class="heading_s1 mb-3">
                            <h6>جمع سبد خرید</h6>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td class="cart_total_label">جمع سبد خرید</td>
                                        <td class="cart_total_amount">{{order.get_total_price}} تومان</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <a href="{% url 'orders:order_pay' order.id %}" class="btn btn-fill-out">ادامه</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END SECTION SHOP -->
    
    </div>
    <!-- END MAIN CONTENT -->

{% endblock content %}