order/urls.py
#==>Library Import
from django.urls import path
#==>Local Import
from . import views


app_name = 'orders'
urlpatterns = [
	path('create/', views.OrderCreateView.as_view(), name='order_create'),
	path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
	path('cart/', views.CartView.as_view(), name='cart'),
	path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
	path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
	path('create/', views.OrderCreateView.as_view(), name='order_create'),
	path('<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
	path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
	path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
	path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon'),

]

product/urls.py
#==>Library Import
from django.urls import path
from . import views


app_name='product'
urlpatterns = [
    path('navbar/', views.NavbarView.as_view(), name='navbar'),
    path('', views.HomeView.as_view(), name='home'),
    path('product/<slug:slug>/', views.ProductDetail.as_view(), name='detail'),
    path('category/<slug:slug>/', views.ProductCategoryList.as_view(), name='category'),
    path('product-list/', views.ProductListView.as_view(), name='product_list'),
    path('about-us/', views.AboutUs.as_view(), name='about-us'),
    path('contact-us/', views.ContactUs.as_view(), name='contact-us'),
]

shop/urls.py
#==>Library Import
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='orders')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
#==>Library Import
from django.db import models
from django.urls import reverse
from ckeditor.fields import RichTextField
from django.utils.html import format_html
from django.conf import settings
#==>Local Import
from extensions.utils import jalali_converter


class TimeStamp(models.Model):
    created = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')
    updated = models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت شده')

    class Meta:
        abstract = True

    def jcreated(self):
        return jalali_converter(self.created)
    jcreated.short_description = 'تاریخ'

    def jupdated(self):
        return jalali_converter(self.updated)


class IPAddress(models.Model):
    ip_address = models.GenericIPAddressField(verbose_name='آی پی آدرس')

    class Meta:
        verbose_name = 'آی پی آدرس'
        verbose_name_plural = 'آی پی آدرس ها'
    
    def __str__(self):
        return self.ip_address


class Category(TimeStamp):
    parent = models.ForeignKey('self', on_delete=models.CASCADE, related_name='category_parent', null=True, blank=True, verbose_name='دسته بندی پدر')
    is_sub = models.BooleanField(default=False, verbose_name='دسته  بندی فرزند؟')
    title = models.CharField(max_length=200, verbose_name='نام')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'

    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' / '.join(full_path[::-1])

    def get_absolute_url(self):
        return reverse('product:category', args=(self.slug,))


class Product(TimeStamp):
    category = models.ManyToManyField(Category, related_name='product_category', verbose_name='دسته بندی')
    title = models.CharField(max_length=200, verbose_name='نام')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')
    description = RichTextField(verbose_name='توضیحات')
    

    class Meta:
        ordering = ('-created',)
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product:detail', args=(self.slug,))

    def image_thumbnail(self):
        return format_html('<img src="{}" width=100 />'.format(self.image.url))
    image_thumbnail.short_description = 'تصویر'


class Color(TimeStamp):
    title = models.CharField(max_length=100, verbose_name='نام رنگ')
    code = models.CharField(max_length=100, blank=True, null=True, verbose_name='کد رنگ')

    class Meta:
        verbose_name = 'رنگ'
        verbose_name_plural = 'رنگ ها'

    def __str__(self):
        return self.title

    def color_tag(self):
        if self.code is not None:
            return format_html('<p style="background-color:{}" />Color</p>'.format(self.code))
        else:
            return ""


class Size(TimeStamp):
    title = models.CharField(max_length=100, verbose_name='نام سایز')

    class Meta:
        verbose_name = 'سایز'
        verbose_name_plural = 'سایز ها'

    def __str__(self):
        return self.title


class Variant(TimeStamp):
    title = models.CharField(max_length=200, verbose_name='نام تنوع')
    slug = models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')
    image = models.ImageField(verbose_name='تصویر')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='variant_product', verbose_name='محصول')
    color = models.ForeignKey(Color, on_delete=models.CASCADE, null=True, blank=True, related_name='variant_color', verbose_name='رنگ')
    size = models.ForeignKey(Size, on_delete=models.CASCADE, null=True, blank=True, related_name='variant_size', verbose_name='سایز')
    quantity = models.IntegerField(default=0, verbose_name='تعداد')
    weight = models.IntegerField(null=True, blank=True, verbose_name='وزن')
    sell = models.IntegerField(default=0, verbose_name='فروش')
    price = models.IntegerField(default=0, verbose_name='قیمت')
    discount = models.IntegerField(verbose_name='تخفیف')
    total_price = models.IntegerField(default=0, null=True, blank=True, verbose_name='قیمت اصلی(تخفیف خورده)')
    visit_count = models.ManyToManyField(IPAddress, blank=True, related_name='visit_count', verbose_name='بازدید')
    available = models.BooleanField(default=True, verbose_name='موجود؟')

    class Meta:
        verbose_name = 'تنوع'
        verbose_name_plural = 'تنوع ها'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.discount:
            self.total_price = self.price
        elif self.discount:
            total = (self.price * self.discount) / 100
            total_price = int(self.price - total)
            self.total_price = total_price
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product:detail', args=(self.slug,))


class Comment(TimeStamp):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comment_user', verbose_name='کاربر')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comment_product', verbose_name='محصول')
    body = models.TextField(verbose_name='متن')

    class Meta:
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت ها'
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user.username} commented {self.body[:10]}'

product/forms.py
#==>Library Import
from django import forms
#==>Local Import
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['body'].widget.attrs.update({'rows': '3', 'placeholder': 'متن پاسخ', 'class':'form-control'})

product/views.py
#==>Library Import
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator
from django.db.models import Max, Min
from django.contrib import messages
from django.db.models import Count
from django.views import View
#==>Local Import
from .models import Category, Variant
from order.forms import CartAddForm
from .filters import ProductFilter
from .forms import CommentForm
from order.cart import Cart


class NavbarView(View):
    def get(self, request):
        categories = Category.objects.filter(is_sub=False)
        cart = Cart(request)
        return render(request, 'inc/navbar.html', {'categories':categories, 'cart':cart})


class HomeView(View):
    def get(self, request):
        products = Variant.objects.filter(available=True)[:8]
        most_sell_products = Variant.objects.order_by('-sell')[:8]
        most_visited_posts = Variant.objects.annotate(p_count=Count('visit_count')).order_by('-p_count')[:8]
        most_visited_posts = Variant.objects.all()
        categories = Category.objects.filter(is_sub=False)
        context = {
            'products':products, 'most_visited_posts': most_visited_posts,
            'most_sell_products':most_sell_products, 'categories':categories,
        }
        return render(request, 'product/home.html', context)


class ProductCategoryList(View):
    def get(self, request, slug):
        category = get_object_or_404(Category, slug=slug)
        products = Variant.objects.filter(product__category=category)
        paginator = Paginator(products, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'product/category_list.html', {'products':page_obj, 'category':category})

class ProductDetail(View):
    form_class = CommentForm

    def setup(self, request, *args, **kwargs):
        self.product_instance = get_object_or_404(Variant, slug=kwargs['slug'])
        return super().setup(request, *args, **kwargs)

    def get(self, request ,*args, **kwargs):
        form = self.form_class
        # Product View Count
        ip_address = request.user.ip_address
        self.product_instance.visit_count.add(ip_address)
        # Product Comments
        comments = self.product_instance.product.comment_product.all()
        cart_form = CartAddForm()
        categories = Category.objects.filter(product_category=self.product_instance.product)
        related_products = Variant.objects.filter(product__category__in=categories)[:8]
        return render(request, 'product/detail.html', {'product':self.product_instance, 'form':form, 'comments':comments, 'cart_form':cart_form, 'related_products':related_products})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.product = self.product_instance.product
            new_comment.save()
            messages.success(request, 'کامنت شما افزوده شد', 'success')
            return redirect('product:detail', kwargs['slug'])


class ProductListView(View):
    def get(self, request):
        categories = Category.objects.filter(is_sub=False)
        products = Variant.objects.all()
        filtered_products = ProductFilter(request.GET, queryset=products)
        products = filtered_products.qs
        mx = Variant.objects.aggregate(price=Max('price'))
        max_price = str(mx['price'])
        mn = Variant.objects.aggregate(price=Min('price'))
        min_price = str(mn['price'])
        paginator = Paginator(products, 1)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'product/product_list.html', {'products':page_obj, 'filter':filtered_products, 'max_price':max_price, 'min_price':min_price, 'categories':categories})


class AboutUs(View):
    def get(self, request):
        return render(request, 'about-us.html')


class ContactUs(View):
    def get(self, request):
        return render(request, 'contact-us.html')

product/templates/product/category_list.html
{% extends 'base.html' %}
{% block title %}دسته بندی {{category.title}}{% endblock title %}

{% block content %}

    <!-- START MAIN CONTENT -->
<div class="main_content">

    <!-- START SECTION SHOP -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="row align-items-center mb-4 pb-1">
                        <div class="col-12">
                            <div class="product_header">
                                <div class="product_header_right">
                                    <div class="products_view">
                                        <a href="javascript:Void(0);" class="shorting_icon grid"><i class="ti-view-grid"></i></a>
                                        <a href="javascript:Void(0);" class="shorting_icon list active"><i class="ti-layout-list-thumb"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div> 
                    <div class="row shop_container list">
                        {% for product in products %}
                        <div class="col-lg-3 col-md-4 col-6">
                            <div class="product">
                                <div class="product_img">
                                    <a href="{{product.get_absolute_url}}">
                                        <img src="{{product.image.url}}" alt="{{product.title}}">
                                    </a>
                                </div>
                                <div class="product_info">
                                    <h6 class="product_title"><a href="{{product.get_absolute_url}}">{{product.title}}</a></h6>
                                    <div class="product_price">
                                        <span class="price">{{product.total_price}} تومان</span>
                                        {% if product.discount != 0 %}
                                            <del>{{product.price}} تومان</del>
                                            <div class="on_sale">
                                                <span>٪{{product.discount}} تخفیف</span>
                                            </div>
                                        {% endif %}
                                    </div>
                                    <div class="pr_desc">
                                        <p>{{product.product.description|striptags|truncatechars:30}}</p>
                                    </div>
                                    <div class="pr_switch_wrap">
                                        <div class="product_color_switch">
                                            <span data-color="{{product.color.code}}"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <ul class="pagination mt-3 justify-content-center pagination_style1">
                                {% if products.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}"><i class="linearicons-arrow-left"></i></a></li>
                                {% endif %}
                                {% if products.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">{{ products.previous_page_number }}</a></li>
                                {% endif %}
                                <li class="page-item"><a class="page-link {% if page_num == page_num %}active {% endif %}" href="?page={{ products.number }}">{{products.number}}</a></li>
                                {% if products.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">{{ products.next_page_number }}</a></li>
                                {% endif %}
                                {% if products.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}"><i class="linearicons-arrow-right"></i></a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END SECTION SHOP -->
    
    </div>
    <!-- END MAIN CONTENT -->

{% endblock content %}

product/templates/product/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}محصول {{product.title}}{% endblock title %}

{% block content %}

    <!-- START MAIN CONTENT -->
<div class="main_content">

    <!-- START SECTION SHOP -->
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 mb-4 mb-md-0">
                  <div class="product-image">
                        <div class="product_img_box">
                            <img id="product_img" src="{{product.image.url}}" data-zoom-image="{{product.image.url}}" alt="{{product.product.title}}" />
                            <a href="#" class="product_img_zoom" title="Zoom">
                                <span class="linearicons-zoom-in"></span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="pr_detail">
                        <div class="product_description">
                            <h4 class="product_title"><a href="#">{{product.title}}</a></h4>
                            <div class="product_price">
                                <span class="price">{{product.total_price}} تومان</span>
                                {% if product.discount != 0 %}
                                <del>{{product.price}} تومان</del>
                                <div class="on_sale">
                                    <span>٪{{product.discount}} تخفیف</span>
                                </div>
                                {% endif %}
                            </div>
                            <div class="rating_wrap">
                                    <div class="rating">
                                        <div class="product_rate" style="width:80%"></div>
                                    </div>
                                    <span class="rating_num">(21)</span>
                                </div>
                            <div class="pr_desc">
                                <p>{{product.product.description|safe|truncatechars:50}}</p>
                            </div>
                            <div class="product_sort_info">
                                <ul>
                                    <li><i class="linearicons-shield-check"></i> 1 سال ضمانت برند الجزیره</li>
                                    <li><i class="linearicons-sync"></i> 30 روز برگشت</li>
                                    <li><i class="linearicons-bag-dollar"></i> پرداخت نقدی موجود است</li>
                                </ul>
                            </div>
                            {% if product.color %}
                            <div class="pr_switch_wrap">
                                <span class="switch_lable">رنگ</span>
                                <div class="product_color_switch">
                                    <span data-color="{{product.color.code}}"></span>
                                </div>
                            </div>
                            {% endif %}
                            {% if product.size %}
                            <div class="pr_switch_wrap">
                                <span class="switch_lable">سایز</span>
                                <div class="product_size_switch">
                                    <span>xs</span>
                                    <span>s</span>
                                    <span>m</span>
                                    <span>l</span>
                                    <span>xl</span>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                        <hr />
                        <div class="cart_extra">
                            <form method="post" action="{% url 'orders:cart_add' product.id %}" class="cart_btn">
                                {% csrf_token %}
                                {{cart_form.quantity}}
                                <button class="btn btn-fill-out btn-addtocart" type="submit"><i class="icon-basket-loaded"></i> افزودن به سبد خرید</button>
                            </form>
                        </div>
                        <hr />
                        <ul class="product-meta">
                            <li>دسته بندی: 
                                {% for category in product.product.category.all %}
                                <a href="{{category.get_absolute_url}}">{{category.title}}</a>
                                {% endfor %}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="large_divider clearfix"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="tab-style3">
                        <ul class="nav nav-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" id="Description-tab" data-toggle="tab" href="#Description" role="tab" aria-controls="Description" aria-selected="true">توضیحات</a>
                              </li>
                              <li class="nav-item">
                                <a class="nav-link" id="Reviews-tab" data-toggle="tab" href="#Reviews" role="tab" aria-controls="Reviews" aria-selected="false">نظرات ({{comments.count}})</a>
                              </li>
                        </ul>
                        <div class="tab-content shop_info_tab">
                              <div class="tab-pane fade show active" id="Description" role="tabpanel" aria-labelledby="Description-tab">
                                <p>{{product.product.description|safe}}</p>
                              </div>
                              <div class="tab-pane fade" id="Reviews" role="tabpanel" aria-labelledby="Reviews-tab">
                                <div class="comments">
                                    <div class="review_form field_form">
                                        <h5>ارسال نظرات</h5>
                                        <h5 class="product_tab_title">{{comments.count}} نظر برای <span>لباس آبی زنانه</span></h5>
                                        <form method="post" class="row mt-3">
                                            {% csrf_token %}
                                            <div class="form-group col-12">
                                                {{form.body}}
                                            </div>
                                            <div class="form-group col-12">
                                                <button type="submit" class="btn btn-fill-out" name="submit" value="Submit">ارسال نظر</button>
                                            </div>
                                        </form>
                                    </div>
                                    <ul class="list_none comment_list mt-4">
                                        {% for comment in comments %}
                                        <li>
                                            <div class="comment_img">
                                                <img src="{{comment.user.profile.image.url}}" alt="user1"/>
                                            </div>
                                            <div class="comment_block">
                                                <p class="customer_meta">
                                                    <span class="review_author">{{comment.user.profile.full_name}}</span>
                                                    <span class="comment-date">{{comment.jcreated}}</span>
                                                </p>
                                                <div class="description">
                                                    <p>{{comment.body}}</p>
                                                </div>
                                            </div>
                                        </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                              </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="small_divider"></div>
                    <div class="divider"></div>
                    <div class="medium_divider"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="heading_s1">
                        <h3>محصولات مرتبط</h3>
                    </div>
                    <div class="releted_product_slider carousel_slider owl-carousel owl-theme" data-margin="20" data-responsive='{"0":{"items": "1"}, "481":{"items": "2"}, "768":{"items": "3"}, "1199":{"items": "4"}}'>
                        {% for product in related_products %}
                        <div class="item">

                            <div class="product">
                                <div class="product_img">
                                    <a href="shop-product-detail.html">
                                        <img src="{{product.image.url}}" alt="product_img1">
                                    </a>
                                    <div class="product_action_box">
                                        <ul class="list_none pr_action_btn">
                                            <li class="add-to-cart"><a href="#"><i class="icon-basket-loaded"></i> افزودن به سبد خرید</a></li>
                                            <li><a href="shop-compare.html"><i class="icon-shuffle"></i></a></li>
                                            <li><a href="shop-quick-view.html" class="popup-ajax"><i class="icon-magnifier-add"></i></a></li>
                                            <li><a href="#"><i class="icon-heart"></i></a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="product_info">
                                    <h6 class="product_title"><a href="shop-product-detail.html">لباس آبی زنانه</a></h6>
                                    <div class="product_price">
                                        <span class="price">45000 تومان</span>
                                        <del>55000 تومان</del>
                                        <div class="on_sale">
                                            <span>٪35 تخفیف</span>
                                        </div>
                                    </div>
                                    <div class="rating_wrap">
                                        <div class="rating">
                                            <div class="product_rate" style="width:80%"></div>
                                        </div>
                                        <span class="rating_num">(21)</span>
                                    </div>
                                    <div class="pr_desc">
                                        <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله.</p>
                                    </div>
                                    <div class="pr_switch_wrap">
                                        <div class="product_color_switch">
                                            <span class="active" data-color="#87554B"></span>
                                            <span data-color="#333333"></span>
                                            <span data-color="#DA323F"></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END SECTION SHOP -->
    
    
    </div>
    <!-- END MAIN CONTENT -->

{% endblock content %}